// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace InjectIntoViewApplication.Models;

public partial class Gender
{
    public int Id { get; set; }

    public string Type { get; set; }
}