
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace InjectIntoViewApplication.Models;

public partial class StateLookup
{
    [Column("StateID")]
    public int Id { get; set; }

    public string StateName { get; set; }

    public string StateAbbrev { get; set; }
}