// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

using ColumnSortApplication.Models;
using Microsoft.EntityFrameworkCore;

namespace ColumnSortApplication.Data;

public partial class Context : DbContext
{
    //public Context()
    //{
    //}

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<BusinessEntityPhone> BusinessEntityPhone { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<ContactDevices> ContactDevices { get; set; }

    public virtual DbSet<ContactType> ContactType { get; set; }

    public virtual DbSet<Contacts> Contacts { get; set; }

    public virtual DbSet<Countries> Countries { get; set; }

    public virtual DbSet<Customers> Customers { get; set; }

    public virtual DbSet<Employees> Employees { get; set; }

    public virtual DbSet<OrderDetails> OrderDetails { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<PhoneType> PhoneType { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<Region> Region { get; set; }

    public virtual DbSet<Shippers> Shippers { get; set; }

    public virtual DbSet<SupplierRegion> SupplierRegion { get; set; }

    public virtual DbSet<Suppliers> Suppliers { get; set; }

    public virtual DbSet<Territories> Territories { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=NorthWind2022;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.BusinessEntityPhoneConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.CategoriesConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.ContactDevicesConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.ContactTypeConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.ContactsConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.CountriesConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.CustomersConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.EmployeesConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.OrderDetailsConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.OrdersConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.PhoneTypeConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.ProductsConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.RegionConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.ShippersConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.SupplierRegionConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.SuppliersConfiguration());
            modelBuilder.ApplyConfiguration(new NorthWindExampleApp4.Data.Configurations.TerritoriesConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
